# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTrain = QtWidgets.QWidget()
        self.tabTrain.setObjectName("tabTrain")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tabTrain)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label = QtWidgets.QLabel(self.tabTrain)
        self.label.setObjectName("label")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.MNISTTrainImgs = QtWidgets.QLineEdit(self.tabTrain)
        self.MNISTTrainImgs.setObjectName("MNISTTrainImgs")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MNISTTrainImgs)
        self.label_2 = QtWidgets.QLabel(self.tabTrain)
        self.label_2.setObjectName("label_2")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.MNISTTestImgs = QtWidgets.QLineEdit(self.tabTrain)
        self.MNISTTestImgs.setObjectName("MNISTTestImgs")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.MNISTTestImgs)
        self.TrainImgEpoch_l = QtWidgets.QLabel(self.tabTrain)
        self.TrainImgEpoch_l.setObjectName("TrainImgEpoch_l")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.TrainImgEpoch_l)
        self.TrainImgEpoch = QtWidgets.QLineEdit(self.tabTrain)
        self.TrainImgEpoch.setObjectName("TrainImgEpoch")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.TrainImgEpoch)
        self.label_4 = QtWidgets.QLabel(self.tabTrain)
        self.label_4.setObjectName("label_4")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.totEpoch = QtWidgets.QLineEdit(self.tabTrain)
        self.totEpoch.setObjectName("totEpoch")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.totEpoch)
        self.label_5 = QtWidgets.QLabel(self.tabTrain)
        self.label_5.setObjectName("label_5")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.intEpoch = QtWidgets.QLineEdit(self.tabTrain)
        self.intEpoch.setObjectName("intEpoch")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.intEpoch)
        self.writeEReport = QtWidgets.QCheckBox(self.tabTrain)
        self.writeEReport.setChecked(True)
        self.writeEReport.setObjectName("writeEReport")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.writeEReport)
        self.label_12 = QtWidgets.QLabel(self.tabTrain)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.SimDynPerf = QtWidgets.QCheckBox(self.tabTrain)
        self.SimDynPerf.setChecked(True)
        self.SimDynPerf.setObjectName("SimDynPerf")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.SimDynPerf)
        self.relaxArrCellH = QtWidgets.QCheckBox(self.tabTrain)
        self.relaxArrCellH.setObjectName("relaxArrCellH")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.relaxArrCellH)
        self.relaxArrCellW = QtWidgets.QCheckBox(self.tabTrain)
        self.relaxArrCellW.setObjectName("relaxArrCellW")
        self.formLayout_8.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.relaxArrCellW)
        self.horizontalLayout_5.addLayout(self.formLayout_8)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setContentsMargins(0, -1, -1, -1)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_6 = QtWidgets.QLabel(self.tabTrain)
        self.label_6.setObjectName("label_6")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.arrWireW = QtWidgets.QLineEdit(self.tabTrain)
        self.arrWireW.setObjectName("arrWireW")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.arrWireW)
        self.label_7 = QtWidgets.QLabel(self.tabTrain)
        self.label_7.setObjectName("label_7")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.node = QtWidgets.QLineEdit(self.tabTrain)
        self.node.setObjectName("node")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.node)
        self.label_8 = QtWidgets.QLabel(self.tabTrain)
        self.label_8.setObjectName("label_8")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.clkfq = QtWidgets.QLineEdit(self.tabTrain)
        self.clkfq.setObjectName("clkfq")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.clkfq)
        self.HWTrainFF = QtWidgets.QCheckBox(self.tabTrain)
        self.HWTrainFF.setChecked(True)
        self.HWTrainFF.setObjectName("HWTrainFF")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HWTrainFF)
        self.HWTrainWU = QtWidgets.QCheckBox(self.tabTrain)
        self.HWTrainWU.setChecked(True)
        self.HWTrainWU.setObjectName("HWTrainWU")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.HWTrainWU)
        self.HWTestFF = QtWidgets.QCheckBox(self.tabTrain)
        self.HWTestFF.setChecked(True)
        self.HWTestFF.setObjectName("HWTestFF")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.HWTestFF)
        self.horizontalLayout_5.addLayout(self.formLayout_9)
        self.tabWidget.addTab(self.tabTrain, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        self.label_33.setObjectName("label_33")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(self.tab_5)
        self.label_34.setObjectName("label_34")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setObjectName("label_35")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        self.label_36.setObjectName("label_36")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.label_37 = QtWidgets.QLabel(self.tab_5)
        self.label_37.setObjectName("label_37")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.label_38 = QtWidgets.QLabel(self.tab_5)
        self.label_38.setObjectName("label_38")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.nIn = QtWidgets.QLineEdit(self.tab_5)
        self.nIn.setObjectName("nIn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nIn)
        self.nHide = QtWidgets.QLineEdit(self.tab_5)
        self.nHide.setObjectName("nHide")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nHide)
        self.nOut = QtWidgets.QLineEdit(self.tab_5)
        self.nOut.setObjectName("nOut")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nOut)
        self.alp1 = QtWidgets.QLineEdit(self.tab_5)
        self.alp1.setObjectName("alp1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.alp1)
        self.alp2 = QtWidgets.QLineEdit(self.tab_5)
        self.alp2.setObjectName("alp2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.alp2)
        self.maxW = QtWidgets.QLineEdit(self.tab_5)
        self.maxW.setObjectName("maxW")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.maxW)
        self.minW = QtWidgets.QLineEdit(self.tab_5)
        self.minW.setObjectName("minW")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.minW)
        self.opt = QtWidgets.QComboBox(self.tab_5)
        self.opt.setObjectName("opt")
        self.opt.addItem("")
        self.opt.addItem("")
        self.opt.addItem("")
        self.opt.addItem("")
        self.opt.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.opt)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(0, -1, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_39 = QtWidgets.QLabel(self.tab_5)
        self.label_39.setObjectName("label_39")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.label_40 = QtWidgets.QLabel(self.tab_5)
        self.label_40.setObjectName("label_40")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.label_41 = QtWidgets.QLabel(self.tab_5)
        self.label_41.setObjectName("label_41")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.label_42 = QtWidgets.QLabel(self.tab_5)
        self.label_42.setObjectName("label_42")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.label_43 = QtWidgets.QLabel(self.tab_5)
        self.label_43.setObjectName("label_43")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.label_44 = QtWidgets.QLabel(self.tab_5)
        self.label_44.setObjectName("label_44")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.label_45 = QtWidgets.QLabel(self.tab_5)
        self.label_45.setObjectName("label_45")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.nBitInput = QtWidgets.QLineEdit(self.tab_5)
        self.nBitInput.setObjectName("nBitInput")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nBitInput)
        self.nBitPartial = QtWidgets.QLineEdit(self.tab_5)
        self.nBitPartial.setObjectName("nBitPartial")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nBitPartial)
        self.nWBit = QtWidgets.QLineEdit(self.tab_5)
        self.nWBit.setObjectName("nWBit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nWBit)
        self.BWthres = QtWidgets.QLineEdit(self.tab_5)
        self.BWthres.setObjectName("BWthres")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.BWthres)
        self.Hthres = QtWidgets.QLineEdit(self.tab_5)
        self.Hthres.setObjectName("Hthres")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Hthres)
        self.nColMux = QtWidgets.QLineEdit(self.tab_5)
        self.nColMux.setObjectName("nColMux")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.nColMux)
        self.nWriteColMux = QtWidgets.QLineEdit(self.tab_5)
        self.nWriteColMux.setObjectName("nWriteColMux")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nWriteColMux)
        self.horizontalLayout_4.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tabIH = QtWidgets.QWidget()
        self.tabIH.setObjectName("tabIH")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabIH)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabIH)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.IHSRAM = QtWidgets.QRadioButton(self.groupBox_3)
        self.IHSRAM.setObjectName("IHSRAM")
        self.gridLayout_6.addWidget(self.IHSRAM, 0, 5, 1, 1)
        self.IHIdeal = QtWidgets.QRadioButton(self.groupBox_3)
        self.IHIdeal.setChecked(True)
        self.IHIdeal.setObjectName("IHIdeal")
        self.gridLayout_6.addWidget(self.IHIdeal, 0, 0, 1, 1)
        self.IHReal = QtWidgets.QRadioButton(self.groupBox_3)
        self.IHReal.setObjectName("IHReal")
        self.gridLayout_6.addWidget(self.IHReal, 0, 1, 1, 1)
        self.IHDigitalNVM = QtWidgets.QRadioButton(self.groupBox_3)
        self.IHDigitalNVM.setObjectName("IHDigitalNVM")
        self.gridLayout_6.addWidget(self.IHDigitalNVM, 0, 3, 1, 1)
        self.IHMeasured = QtWidgets.QRadioButton(self.groupBox_3)
        self.IHMeasured.setObjectName("IHMeasured")
        self.gridLayout_6.addWidget(self.IHMeasured, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tabIH)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.formLayout_18 = QtWidgets.QFormLayout()
        self.formLayout_18.setObjectName("formLayout_18")
        self.label_76 = QtWidgets.QLabel(self.tab_4)
        self.label_76.setObjectName("label_76")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_76)
        self.IHDevMaxConductance = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevMaxConductance.setObjectName("IHDevMaxConductance")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevMaxConductance)
        self.label_78 = QtWidgets.QLabel(self.tab_4)
        self.label_78.setObjectName("label_78")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_78)
        self.IHDevMinConductance = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevMinConductance.setObjectName("IHDevMinConductance")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevMinConductance)
        self.label_79 = QtWidgets.QLabel(self.tab_4)
        self.label_79.setObjectName("label_79")
        self.formLayout_18.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_79)
        self.IHDevReadVoltage = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevReadVoltage.setObjectName("IHDevReadVoltage")
        self.formLayout_18.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IHDevReadVoltage)
        self.label_81 = QtWidgets.QLabel(self.tab_4)
        self.label_81.setObjectName("label_81")
        self.formLayout_18.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_81)
        self.IHDevReadPulseWidth = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevReadPulseWidth.setObjectName("IHDevReadPulseWidth")
        self.formLayout_18.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.IHDevReadPulseWidth)
        self.label_82 = QtWidgets.QLabel(self.tab_4)
        self.label_82.setObjectName("label_82")
        self.formLayout_18.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_82)
        self.IHDevWriteVoltageLTP = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevWriteVoltageLTP.setObjectName("IHDevWriteVoltageLTP")
        self.formLayout_18.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.IHDevWriteVoltageLTP)
        self.label_83 = QtWidgets.QLabel(self.tab_4)
        self.label_83.setObjectName("label_83")
        self.formLayout_18.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_83)
        self.IHDevWriteVoltageLTD = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevWriteVoltageLTD.setObjectName("IHDevWriteVoltageLTD")
        self.formLayout_18.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.IHDevWriteVoltageLTD)
        self.label_84 = QtWidgets.QLabel(self.tab_4)
        self.label_84.setObjectName("label_84")
        self.formLayout_18.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_84)
        self.IHDevWritePulseWidthLTP = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevWritePulseWidthLTP.setObjectName("IHDevWritePulseWidthLTP")
        self.formLayout_18.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.IHDevWritePulseWidthLTP)
        self.label_80 = QtWidgets.QLabel(self.tab_4)
        self.label_80.setObjectName("label_80")
        self.formLayout_18.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_80)
        self.IHDevWritePulseWidthLTD = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevWritePulseWidthLTD.setObjectName("IHDevWritePulseWidthLTD")
        self.formLayout_18.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.IHDevWritePulseWidthLTD)
        self.horizontalLayout_8.addLayout(self.formLayout_18)
        self.formLayout_19 = QtWidgets.QFormLayout()
        self.formLayout_19.setObjectName("formLayout_19")
        self.label_77 = QtWidgets.QLabel(self.tab_4)
        self.label_77.setObjectName("label_77")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_77)
        self.IHDevReadEnergy = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevReadEnergy.setObjectName("IHDevReadEnergy")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevReadEnergy)
        self.label_85 = QtWidgets.QLabel(self.tab_4)
        self.label_85.setObjectName("label_85")
        self.formLayout_19.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_85)
        self.IHDevWriteEnergy = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevWriteEnergy.setObjectName("IHDevWriteEnergy")
        self.formLayout_19.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevWriteEnergy)
        self.label_89 = QtWidgets.QLabel(self.tab_4)
        self.label_89.setObjectName("label_89")
        self.formLayout_19.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_89)
        self.IHDevResistanceAccess = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevResistanceAccess.setObjectName("IHDevResistanceAccess")
        self.formLayout_19.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IHDevResistanceAccess)
        self.label_91 = QtWidgets.QLabel(self.tab_4)
        self.label_91.setObjectName("label_91")
        self.formLayout_19.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_91)
        self.IHDevNL = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevNL.setObjectName("IHDevNL")
        self.formLayout_19.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.IHDevNL)
        self.label_86 = QtWidgets.QLabel(self.tab_4)
        self.label_86.setObjectName("label_86")
        self.formLayout_19.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_86)
        self.IHDevSigmaReadNoise = QtWidgets.QLineEdit(self.tab_4)
        self.IHDevSigmaReadNoise.setObjectName("IHDevSigmaReadNoise")
        self.formLayout_19.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.IHDevSigmaReadNoise)
        self.IHDevCMOSAccess = QtWidgets.QCheckBox(self.tab_4)
        self.IHDevCMOSAccess.setChecked(True)
        self.IHDevCMOSAccess.setObjectName("IHDevCMOSAccess")
        self.formLayout_19.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.IHDevCMOSAccess)
        self.IHDevNonlinearIV = QtWidgets.QCheckBox(self.tab_4)
        self.IHDevNonlinearIV.setObjectName("IHDevNonlinearIV")
        self.formLayout_19.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.IHDevNonlinearIV)
        self.IHDevReadNoise = QtWidgets.QCheckBox(self.tab_4)
        self.IHDevReadNoise.setObjectName("IHDevReadNoise")
        self.formLayout_19.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.IHDevReadNoise)
        self.horizontalLayout_8.addLayout(self.formLayout_19)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.IHDevMaxNumLevelLTP = QtWidgets.QLineEdit(self.tab)
        self.IHDevMaxNumLevelLTP.setObjectName("IHDevMaxNumLevelLTP")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevMaxNumLevelLTP)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.IHDevMaxNumLevelLTD = QtWidgets.QLineEdit(self.tab)
        self.IHDevMaxNumLevelLTD.setObjectName("IHDevMaxNumLevelLTD")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevMaxNumLevelLTD)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.IHDevNumPulse = QtWidgets.QLineEdit(self.tab)
        self.IHDevNumPulse.setObjectName("IHDevNumPulse")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IHDevNumPulse)
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.IHDevGateCapFeFET = QtWidgets.QLineEdit(self.tab)
        self.IHDevGateCapFeFET.setObjectName("IHDevGateCapFeFET")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.IHDevGateCapFeFET)
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.IHDevResistanceAccess_2 = QtWidgets.QLineEdit(self.tab)
        self.IHDevResistanceAccess_2.setObjectName("IHDevResistanceAccess_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.IHDevResistanceAccess_2)
        self.IHDevCMOSAccess_2 = QtWidgets.QCheckBox(self.tab)
        self.IHDevCMOSAccess_2.setChecked(True)
        self.IHDevCMOSAccess_2.setObjectName("IHDevCMOSAccess_2")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.IHDevCMOSAccess_2)
        self.IHDevFeFET = QtWidgets.QCheckBox(self.tab)
        self.IHDevFeFET.setObjectName("IHDevFeFET")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.IHDevFeFET)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.IHDevMaxConductanceVar = QtWidgets.QLineEdit(self.tab)
        self.IHDevMaxConductanceVar.setObjectName("IHDevMaxConductanceVar")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevMaxConductanceVar)
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.IHDevMinConductanceVar = QtWidgets.QLineEdit(self.tab)
        self.IHDevMinConductanceVar.setObjectName("IHDevMinConductanceVar")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevMinConductanceVar)
        self.IHDevNonlinearIV_2 = QtWidgets.QCheckBox(self.tab)
        self.IHDevNonlinearIV_2.setObjectName("IHDevNonlinearIV_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.IHDevNonlinearIV_2)
        self.IHDevNonIdenticalPulse = QtWidgets.QCheckBox(self.tab)
        self.IHDevNonIdenticalPulse.setObjectName("IHDevNonIdenticalPulse")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.IHDevNonIdenticalPulse)
        self.IHDevConductanceRangeVar = QtWidgets.QCheckBox(self.tab)
        self.IHDevConductanceRangeVar.setObjectName("IHDevConductanceRangeVar")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IHDevConductanceRangeVar)
        self.horizontalLayout_2.addLayout(self.formLayout_4)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_59 = QtWidgets.QLabel(self.tab_2)
        self.label_59.setObjectName("label_59")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_59)
        self.IHDevVinitLTP = QtWidgets.QLineEdit(self.tab_2)
        self.IHDevVinitLTP.setObjectName("IHDevVinitLTP")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevVinitLTP)
        self.label_60 = QtWidgets.QLabel(self.tab_2)
        self.label_60.setObjectName("label_60")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_60)
        self.IHDevVstepLTP = QtWidgets.QLineEdit(self.tab_2)
        self.IHDevVstepLTP.setObjectName("IHDevVstepLTP")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevVstepLTP)
        self.label_61 = QtWidgets.QLabel(self.tab_2)
        self.label_61.setObjectName("label_61")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.IHDevVinitLTD = QtWidgets.QLineEdit(self.tab_2)
        self.IHDevVinitLTD.setObjectName("IHDevVinitLTD")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IHDevVinitLTD)
        self.label_62 = QtWidgets.QLabel(self.tab_2)
        self.label_62.setObjectName("label_62")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_62)
        self.IHDevVstepLTD = QtWidgets.QLineEdit(self.tab_2)
        self.IHDevVstepLTD.setObjectName("IHDevVstepLTD")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.IHDevVstepLTD)
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        self.label_63.setObjectName("label_63")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_63)
        self.IHDevPWinitLTP = QtWidgets.QLineEdit(self.tab_2)
        self.IHDevPWinitLTP.setObjectName("IHDevPWinitLTP")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.IHDevPWinitLTP)
        self.label_64 = QtWidgets.QLabel(self.tab_2)
        self.label_64.setObjectName("label_64")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.IHDevPWstepLTP = QtWidgets.QLineEdit(self.tab_2)
        self.IHDevPWstepLTP.setObjectName("IHDevPWstepLTP")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.IHDevPWstepLTP)
        self.IHDevNonlinearWrite = QtWidgets.QCheckBox(self.tab_2)
        self.IHDevNonlinearWrite.setChecked(True)
        self.IHDevNonlinearWrite.setObjectName("IHDevNonlinearWrite")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.IHDevNonlinearWrite)
        self.horizontalLayout_7.addLayout(self.formLayout_7)
        self.formLayout_15 = QtWidgets.QFormLayout()
        self.formLayout_15.setObjectName("formLayout_15")
        self.label_58 = QtWidgets.QLabel(self.tab_2)
        self.label_58.setObjectName("label_58")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_58)
        self.IHDevPWinitLTD = QtWidgets.QLineEdit(self.tab_2)
        self.IHDevPWinitLTD.setObjectName("IHDevPWinitLTD")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevPWinitLTD)
        self.label_65 = QtWidgets.QLabel(self.tab_2)
        self.label_65.setObjectName("label_65")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_65)
        self.IHDevPWstepLTD = QtWidgets.QLineEdit(self.tab_2)
        self.IHDevPWstepLTD.setObjectName("IHDevPWstepLTD")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevPWstepLTD)
        self.label_66 = QtWidgets.QLabel(self.tab_2)
        self.label_66.setObjectName("label_66")
        self.formLayout_15.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_66)
        self.IHDevWriteVoltageSquareSum = QtWidgets.QLineEdit(self.tab_2)
        self.IHDevWriteVoltageSquareSum.setObjectName("IHDevWriteVoltageSquareSum")
        self.formLayout_15.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IHDevWriteVoltageSquareSum)
        self.label_67 = QtWidgets.QLabel(self.tab_2)
        self.label_67.setObjectName("label_67")
        self.formLayout_15.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_67)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.formLayout_15.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_67)
        self.label_68 = QtWidgets.QLabel(self.tab_2)
        self.label_68.setObjectName("label_68")
        self.formLayout_15.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_68)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.formLayout_15.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_68)
        self.horizontalLayout_7.addLayout(self.formLayout_15)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout_16 = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout_16.setObjectName("formLayout_16")
        self.label_70 = QtWidgets.QLabel(self.tab_3)
        self.label_70.setObjectName("label_70")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_70)
        self.label_71 = QtWidgets.QLabel(self.tab_3)
        self.label_71.setObjectName("label_71")
        self.formLayout_16.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_71)
        self.IHDevBit = QtWidgets.QLineEdit(self.tab_3)
        self.IHDevBit.setObjectName("IHDevBit")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevBit)
        self.IHDevBitPrev = QtWidgets.QLineEdit(self.tab_3)
        self.IHDevBitPrev.setObjectName("IHDevBitPrev")
        self.formLayout_16.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevBitPrev)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_13 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_13.setObjectName("formLayout_13")
        self.IHDevParallelRead = QtWidgets.QCheckBox(self.groupBox_2)
        self.IHDevParallelRead.setObjectName("IHDevParallelRead")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.IHDevParallelRead)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_10 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_46 = QtWidgets.QLabel(self.groupBox)
        self.label_46.setObjectName("label_46")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.label_50 = QtWidgets.QLabel(self.groupBox)
        self.label_50.setObjectName("label_50")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.label_51 = QtWidgets.QLabel(self.groupBox)
        self.label_51.setObjectName("label_51")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.IHDevNLLTP = QtWidgets.QLineEdit(self.groupBox)
        self.IHDevNLLTP.setObjectName("IHDevNLLTP")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevNLLTP)
        self.IHDevNLLTD = QtWidgets.QLineEdit(self.groupBox)
        self.IHDevNLLTD.setObjectName("IHDevNLLTD")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevNLLTD)
        self.IHDevSigmaDtoD = QtWidgets.QLineEdit(self.groupBox)
        self.IHDevSigmaDtoD.setObjectName("IHDevSigmaDtoD")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IHDevSigmaDtoD)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_2)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setContentsMargins(0, -1, -1, -1)
        self.formLayout_12.setObjectName("formLayout_12")
        self.label_52 = QtWidgets.QLabel(self.groupBox_4)
        self.label_52.setObjectName("label_52")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.IHDevHeightInFeatureSize = QtWidgets.QLineEdit(self.groupBox_4)
        self.IHDevHeightInFeatureSize.setObjectName("IHDevHeightInFeatureSize")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevHeightInFeatureSize)
        self.label_53 = QtWidgets.QLabel(self.groupBox_4)
        self.label_53.setObjectName("label_53")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.label_55 = QtWidgets.QLabel(self.groupBox_4)
        self.label_55.setObjectName("label_55")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.IHDevWidthInFeatureSize = QtWidgets.QLineEdit(self.groupBox_4)
        self.IHDevWidthInFeatureSize.setObjectName("IHDevWidthInFeatureSize")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevWidthInFeatureSize)
        self.IHDevWidthSRAMCellNMOS = QtWidgets.QLineEdit(self.groupBox_4)
        self.IHDevWidthSRAMCellNMOS.setObjectName("IHDevWidthSRAMCellNMOS")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IHDevWidthSRAMCellNMOS)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.formLayout_12.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.IHDevReadEnergySRAMCell = QtWidgets.QLineEdit(self.groupBox_4)
        self.IHDevReadEnergySRAMCell.setObjectName("IHDevReadEnergySRAMCell")
        self.formLayout_12.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.IHDevReadEnergySRAMCell)
        self.horizontalLayout_6.addLayout(self.formLayout_12)
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setObjectName("formLayout_14")
        self.label_48 = QtWidgets.QLabel(self.groupBox_4)
        self.label_48.setObjectName("label_48")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.IHDevWidthSRAMCellPMOS = QtWidgets.QLineEdit(self.groupBox_4)
        self.IHDevWidthSRAMCellPMOS.setObjectName("IHDevWidthSRAMCellPMOS")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevWidthSRAMCellPMOS)
        self.label_54 = QtWidgets.QLabel(self.groupBox_4)
        self.label_54.setObjectName("label_54")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.label_56 = QtWidgets.QLabel(self.groupBox_4)
        self.label_56.setObjectName("label_56")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.IHDevWidthAccessCMOS = QtWidgets.QLineEdit(self.groupBox_4)
        self.IHDevWidthAccessCMOS.setObjectName("IHDevWidthAccessCMOS")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IHDevWidthAccessCMOS)
        self.IHDevMinSenseVoltage = QtWidgets.QLineEdit(self.groupBox_4)
        self.IHDevMinSenseVoltage.setObjectName("IHDevMinSenseVoltage")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IHDevMinSenseVoltage)
        self.IHDevWriteEnergySRAMCell = QtWidgets.QLineEdit(self.groupBox_4)
        self.IHDevWriteEnergySRAMCell.setObjectName("IHDevWriteEnergySRAMCell")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.IHDevWriteEnergySRAMCell)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_6.addLayout(self.formLayout_14)
        self.gridLayout_3.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_11 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_11.setObjectName("formLayout_11")
        self.IHDevSymLTPandLTD = QtWidgets.QCheckBox(self.groupBox_5)
        self.IHDevSymLTPandLTD.setObjectName("IHDevSymLTPandLTD")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IHDevSymLTPandLTD)
        self.gridLayout_3.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tabIH, "")
        self.tabHO = QtWidgets.QWidget()
        self.tabHO.setObjectName("tabHO")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabHO)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tabHO)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.HOReal = QtWidgets.QRadioButton(self.groupBox_10)
        self.HOReal.setObjectName("HOReal")
        self.gridLayout_7.addWidget(self.HOReal, 0, 1, 1, 1)
        self.HODigitalNVM = QtWidgets.QRadioButton(self.groupBox_10)
        self.HODigitalNVM.setObjectName("HODigitalNVM")
        self.gridLayout_7.addWidget(self.HODigitalNVM, 0, 3, 1, 1)
        self.HOIdeal = QtWidgets.QRadioButton(self.groupBox_10)
        self.HOIdeal.setChecked(True)
        self.HOIdeal.setObjectName("HOIdeal")
        self.gridLayout_7.addWidget(self.HOIdeal, 0, 0, 1, 1)
        self.HOSRAM = QtWidgets.QRadioButton(self.groupBox_10)
        self.HOSRAM.setObjectName("HOSRAM")
        self.gridLayout_7.addWidget(self.HOSRAM, 0, 5, 1, 1)
        self.HOMeasured = QtWidgets.QRadioButton(self.groupBox_10)
        self.HOMeasured.setObjectName("HOMeasured")
        self.gridLayout_7.addWidget(self.HOMeasured, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tabHO)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.formLayout_20 = QtWidgets.QFormLayout()
        self.formLayout_20.setObjectName("formLayout_20")
        self.label_92 = QtWidgets.QLabel(self.tab_7)
        self.label_92.setObjectName("label_92")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_92)
        self.HODevMaxConductance = QtWidgets.QLineEdit(self.tab_7)
        self.HODevMaxConductance.setObjectName("HODevMaxConductance")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevMaxConductance)
        self.label_93 = QtWidgets.QLabel(self.tab_7)
        self.label_93.setObjectName("label_93")
        self.formLayout_20.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_93)
        self.label_94 = QtWidgets.QLabel(self.tab_7)
        self.label_94.setObjectName("label_94")
        self.formLayout_20.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_94)
        self.label_95 = QtWidgets.QLabel(self.tab_7)
        self.label_95.setObjectName("label_95")
        self.formLayout_20.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_95)
        self.label_96 = QtWidgets.QLabel(self.tab_7)
        self.label_96.setObjectName("label_96")
        self.formLayout_20.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_96)
        self.label_97 = QtWidgets.QLabel(self.tab_7)
        self.label_97.setObjectName("label_97")
        self.formLayout_20.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_97)
        self.label_98 = QtWidgets.QLabel(self.tab_7)
        self.label_98.setObjectName("label_98")
        self.formLayout_20.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_98)
        self.label_99 = QtWidgets.QLabel(self.tab_7)
        self.label_99.setObjectName("label_99")
        self.formLayout_20.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_99)
        self.HODevMinConductance = QtWidgets.QLineEdit(self.tab_7)
        self.HODevMinConductance.setObjectName("HODevMinConductance")
        self.formLayout_20.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevMinConductance)
        self.HODevReadVoltage = QtWidgets.QLineEdit(self.tab_7)
        self.HODevReadVoltage.setObjectName("HODevReadVoltage")
        self.formLayout_20.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HODevReadVoltage)
        self.HODevReadPulseWidth = QtWidgets.QLineEdit(self.tab_7)
        self.HODevReadPulseWidth.setObjectName("HODevReadPulseWidth")
        self.formLayout_20.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HODevReadPulseWidth)
        self.HODevWriteVoltageLTP = QtWidgets.QLineEdit(self.tab_7)
        self.HODevWriteVoltageLTP.setObjectName("HODevWriteVoltageLTP")
        self.formLayout_20.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.HODevWriteVoltageLTP)
        self.HODevWriteVoltageLTD = QtWidgets.QLineEdit(self.tab_7)
        self.HODevWriteVoltageLTD.setObjectName("HODevWriteVoltageLTD")
        self.formLayout_20.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.HODevWriteVoltageLTD)
        self.HODevWritePulseWidthLTP = QtWidgets.QLineEdit(self.tab_7)
        self.HODevWritePulseWidthLTP.setObjectName("HODevWritePulseWidthLTP")
        self.formLayout_20.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.HODevWritePulseWidthLTP)
        self.HODevWritePulseWidthLTD = QtWidgets.QLineEdit(self.tab_7)
        self.HODevWritePulseWidthLTD.setObjectName("HODevWritePulseWidthLTD")
        self.formLayout_20.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.HODevWritePulseWidthLTD)
        self.horizontalLayout_9.addLayout(self.formLayout_20)
        self.formLayout_21 = QtWidgets.QFormLayout()
        self.formLayout_21.setObjectName("formLayout_21")
        self.label_100 = QtWidgets.QLabel(self.tab_7)
        self.label_100.setObjectName("label_100")
        self.formLayout_21.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_100)
        self.HODevReadEnergy = QtWidgets.QLineEdit(self.tab_7)
        self.HODevReadEnergy.setObjectName("HODevReadEnergy")
        self.formLayout_21.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevReadEnergy)
        self.label_101 = QtWidgets.QLabel(self.tab_7)
        self.label_101.setObjectName("label_101")
        self.formLayout_21.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_101)
        self.HODevWriteEnergy = QtWidgets.QLineEdit(self.tab_7)
        self.HODevWriteEnergy.setObjectName("HODevWriteEnergy")
        self.formLayout_21.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevWriteEnergy)
        self.label_105 = QtWidgets.QLabel(self.tab_7)
        self.label_105.setObjectName("label_105")
        self.formLayout_21.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_105)
        self.HODevResistanceAccess = QtWidgets.QLineEdit(self.tab_7)
        self.HODevResistanceAccess.setObjectName("HODevResistanceAccess")
        self.formLayout_21.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HODevResistanceAccess)
        self.label_107 = QtWidgets.QLabel(self.tab_7)
        self.label_107.setObjectName("label_107")
        self.formLayout_21.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_107)
        self.HODevNL = QtWidgets.QLineEdit(self.tab_7)
        self.HODevNL.setObjectName("HODevNL")
        self.formLayout_21.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HODevNL)
        self.label_102 = QtWidgets.QLabel(self.tab_7)
        self.label_102.setObjectName("label_102")
        self.formLayout_21.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_102)
        self.HODevSigmaReadNoise = QtWidgets.QLineEdit(self.tab_7)
        self.HODevSigmaReadNoise.setObjectName("HODevSigmaReadNoise")
        self.formLayout_21.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.HODevSigmaReadNoise)
        self.HODevCMOSAccess = QtWidgets.QCheckBox(self.tab_7)
        self.HODevCMOSAccess.setChecked(True)
        self.HODevCMOSAccess.setObjectName("HODevCMOSAccess")
        self.formLayout_21.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.HODevCMOSAccess)
        self.HODevNonlinearIV = QtWidgets.QCheckBox(self.tab_7)
        self.HODevNonlinearIV.setObjectName("HODevNonlinearIV")
        self.formLayout_21.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.HODevNonlinearIV)
        self.HODevReadNoise = QtWidgets.QCheckBox(self.tab_7)
        self.HODevReadNoise.setObjectName("HODevReadNoise")
        self.formLayout_21.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.HODevReadNoise)
        self.horizontalLayout_9.addLayout(self.formLayout_21)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_28 = QtWidgets.QFormLayout()
        self.formLayout_28.setObjectName("formLayout_28")
        self.label_125 = QtWidgets.QLabel(self.tab_9)
        self.label_125.setObjectName("label_125")
        self.formLayout_28.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_125)
        self.HODevMaxNumLevelLTP = QtWidgets.QLineEdit(self.tab_9)
        self.HODevMaxNumLevelLTP.setObjectName("HODevMaxNumLevelLTP")
        self.formLayout_28.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevMaxNumLevelLTP)
        self.label_126 = QtWidgets.QLabel(self.tab_9)
        self.label_126.setObjectName("label_126")
        self.formLayout_28.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_126)
        self.HODevMaxNumLevelLTD = QtWidgets.QLineEdit(self.tab_9)
        self.HODevMaxNumLevelLTD.setObjectName("HODevMaxNumLevelLTD")
        self.formLayout_28.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevMaxNumLevelLTD)
        self.label_127 = QtWidgets.QLabel(self.tab_9)
        self.label_127.setObjectName("label_127")
        self.formLayout_28.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_127)
        self.HODevNumPulse = QtWidgets.QLineEdit(self.tab_9)
        self.HODevNumPulse.setObjectName("HODevNumPulse")
        self.formLayout_28.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HODevNumPulse)
        self.label_130 = QtWidgets.QLabel(self.tab_9)
        self.label_130.setObjectName("label_130")
        self.formLayout_28.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_130)
        self.HODevGateCapFeFET = QtWidgets.QLineEdit(self.tab_9)
        self.HODevGateCapFeFET.setObjectName("HODevGateCapFeFET")
        self.formLayout_28.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HODevGateCapFeFET)
        self.label_131 = QtWidgets.QLabel(self.tab_9)
        self.label_131.setObjectName("label_131")
        self.formLayout_28.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_131)
        self.HODevResistanceAccess_2 = QtWidgets.QLineEdit(self.tab_9)
        self.HODevResistanceAccess_2.setObjectName("HODevResistanceAccess_2")
        self.formLayout_28.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.HODevResistanceAccess_2)
        self.HODevCMOSAccess_2 = QtWidgets.QCheckBox(self.tab_9)
        self.HODevCMOSAccess_2.setChecked(True)
        self.HODevCMOSAccess_2.setObjectName("HODevCMOSAccess_2")
        self.formLayout_28.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.HODevCMOSAccess_2)
        self.HODevFeFET = QtWidgets.QCheckBox(self.tab_9)
        self.HODevFeFET.setObjectName("HODevFeFET")
        self.formLayout_28.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.HODevFeFET)
        self.horizontalLayout_3.addLayout(self.formLayout_28)
        self.formLayout_27 = QtWidgets.QFormLayout()
        self.formLayout_27.setObjectName("formLayout_27")
        self.label_123 = QtWidgets.QLabel(self.tab_9)
        self.label_123.setObjectName("label_123")
        self.formLayout_27.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_123)
        self.HODevMaxConductanceVar = QtWidgets.QLineEdit(self.tab_9)
        self.HODevMaxConductanceVar.setObjectName("HODevMaxConductanceVar")
        self.formLayout_27.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevMaxConductanceVar)
        self.label_124 = QtWidgets.QLabel(self.tab_9)
        self.label_124.setObjectName("label_124")
        self.formLayout_27.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_124)
        self.HODevMinConductanceVar = QtWidgets.QLineEdit(self.tab_9)
        self.HODevMinConductanceVar.setObjectName("HODevMinConductanceVar")
        self.formLayout_27.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevMinConductanceVar)
        self.HODevConductanceRangeVar = QtWidgets.QCheckBox(self.tab_9)
        self.HODevConductanceRangeVar.setObjectName("HODevConductanceRangeVar")
        self.formLayout_27.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HODevConductanceRangeVar)
        self.HODevNonlinearIV_2 = QtWidgets.QCheckBox(self.tab_9)
        self.HODevNonlinearIV_2.setObjectName("HODevNonlinearIV_2")
        self.formLayout_27.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HODevNonlinearIV_2)
        self.HODevNonIdenticalPulse = QtWidgets.QCheckBox(self.tab_9)
        self.HODevNonIdenticalPulse.setObjectName("HODevNonIdenticalPulse")
        self.formLayout_27.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.HODevNonIdenticalPulse)
        self.horizontalLayout_3.addLayout(self.formLayout_27)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.formLayout_29 = QtWidgets.QFormLayout()
        self.formLayout_29.setObjectName("formLayout_29")
        self.label_133 = QtWidgets.QLabel(self.tab_10)
        self.label_133.setObjectName("label_133")
        self.formLayout_29.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_133)
        self.HODevVinitLTP = QtWidgets.QLineEdit(self.tab_10)
        self.HODevVinitLTP.setObjectName("HODevVinitLTP")
        self.formLayout_29.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevVinitLTP)
        self.label_134 = QtWidgets.QLabel(self.tab_10)
        self.label_134.setObjectName("label_134")
        self.formLayout_29.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_134)
        self.HODevVstepLTP = QtWidgets.QLineEdit(self.tab_10)
        self.HODevVstepLTP.setObjectName("HODevVstepLTP")
        self.formLayout_29.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevVstepLTP)
        self.label_135 = QtWidgets.QLabel(self.tab_10)
        self.label_135.setObjectName("label_135")
        self.formLayout_29.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_135)
        self.HODevVinitLTD = QtWidgets.QLineEdit(self.tab_10)
        self.HODevVinitLTD.setObjectName("HODevVinitLTD")
        self.formLayout_29.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HODevVinitLTD)
        self.label_136 = QtWidgets.QLabel(self.tab_10)
        self.label_136.setObjectName("label_136")
        self.formLayout_29.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_136)
        self.HODevVstepLTD = QtWidgets.QLineEdit(self.tab_10)
        self.HODevVstepLTD.setObjectName("HODevVstepLTD")
        self.formLayout_29.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HODevVstepLTD)
        self.label_137 = QtWidgets.QLabel(self.tab_10)
        self.label_137.setObjectName("label_137")
        self.formLayout_29.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_137)
        self.HODevPWinitLTP = QtWidgets.QLineEdit(self.tab_10)
        self.HODevPWinitLTP.setObjectName("HODevPWinitLTP")
        self.formLayout_29.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.HODevPWinitLTP)
        self.label_138 = QtWidgets.QLabel(self.tab_10)
        self.label_138.setObjectName("label_138")
        self.formLayout_29.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_138)
        self.HODevPWstepLTP = QtWidgets.QLineEdit(self.tab_10)
        self.HODevPWstepLTP.setObjectName("HODevPWstepLTP")
        self.formLayout_29.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.HODevPWstepLTP)
        self.HODevNonlinearWrite = QtWidgets.QCheckBox(self.tab_10)
        self.HODevNonlinearWrite.setChecked(True)
        self.HODevNonlinearWrite.setObjectName("HODevNonlinearWrite")
        self.formLayout_29.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.HODevNonlinearWrite)
        self.horizontalLayout_11.addLayout(self.formLayout_29)
        self.formLayout_30 = QtWidgets.QFormLayout()
        self.formLayout_30.setObjectName("formLayout_30")
        self.label_139 = QtWidgets.QLabel(self.tab_10)
        self.label_139.setObjectName("label_139")
        self.formLayout_30.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_139)
        self.HODevPWinitLTD = QtWidgets.QLineEdit(self.tab_10)
        self.HODevPWinitLTD.setObjectName("HODevPWinitLTD")
        self.formLayout_30.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevPWinitLTD)
        self.label_140 = QtWidgets.QLabel(self.tab_10)
        self.label_140.setObjectName("label_140")
        self.formLayout_30.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_140)
        self.HODevPWstepLTD = QtWidgets.QLineEdit(self.tab_10)
        self.HODevPWstepLTD.setObjectName("HODevPWstepLTD")
        self.formLayout_30.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevPWstepLTD)
        self.label_141 = QtWidgets.QLabel(self.tab_10)
        self.label_141.setObjectName("label_141")
        self.formLayout_30.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_141)
        self.HODevWriteVoltageSquareSum = QtWidgets.QLineEdit(self.tab_10)
        self.HODevWriteVoltageSquareSum.setObjectName("HODevWriteVoltageSquareSum")
        self.formLayout_30.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HODevWriteVoltageSquareSum)
        self.label_142 = QtWidgets.QLabel(self.tab_10)
        self.label_142.setObjectName("label_142")
        self.formLayout_30.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_142)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_30.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_143 = QtWidgets.QLabel(self.tab_10)
        self.label_143.setObjectName("label_143")
        self.formLayout_30.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_143)
        self.lineEdit_143 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_143.setObjectName("lineEdit_143")
        self.formLayout_30.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_143)
        self.horizontalLayout_11.addLayout(self.formLayout_30)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.formLayout_31 = QtWidgets.QFormLayout(self.tab_11)
        self.formLayout_31.setObjectName("formLayout_31")
        self.label_145 = QtWidgets.QLabel(self.tab_11)
        self.label_145.setObjectName("label_145")
        self.formLayout_31.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_145)
        self.label_146 = QtWidgets.QLabel(self.tab_11)
        self.label_146.setObjectName("label_146")
        self.formLayout_31.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_146)
        self.HODevBit = QtWidgets.QLineEdit(self.tab_11)
        self.HODevBit.setObjectName("HODevBit")
        self.formLayout_31.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevBit)
        self.HODevBitPrev = QtWidgets.QLineEdit(self.tab_11)
        self.HODevBitPrev.setObjectName("HODevBitPrev")
        self.formLayout_31.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevBitPrev)
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayout_26 = QtWidgets.QFormLayout(self.groupBox_9)
        self.formLayout_26.setObjectName("formLayout_26")
        self.HODevSymLTPandLTD = QtWidgets.QCheckBox(self.groupBox_9)
        self.HODevSymLTPandLTD.setObjectName("HODevSymLTPandLTD")
        self.formLayout_26.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.HODevSymLTPandLTD)
        self.gridLayout_5.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_22 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_22.setObjectName("formLayout_22")
        self.HODevParallelRead = QtWidgets.QCheckBox(self.groupBox_6)
        self.HODevParallelRead.setObjectName("HODevParallelRead")
        self.formLayout_22.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.HODevParallelRead)
        self.gridLayout_5.addWidget(self.groupBox_6, 2, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.formLayout_24 = QtWidgets.QFormLayout()
        self.formLayout_24.setContentsMargins(0, -1, -1, -1)
        self.formLayout_24.setObjectName("formLayout_24")
        self.label_113 = QtWidgets.QLabel(self.groupBox_8)
        self.label_113.setObjectName("label_113")
        self.formLayout_24.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_113)
        self.HODevHeightInFeatureSize = QtWidgets.QLineEdit(self.groupBox_8)
        self.HODevHeightInFeatureSize.setObjectName("HODevHeightInFeatureSize")
        self.formLayout_24.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevHeightInFeatureSize)
        self.label_114 = QtWidgets.QLabel(self.groupBox_8)
        self.label_114.setObjectName("label_114")
        self.formLayout_24.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_114)
        self.label_115 = QtWidgets.QLabel(self.groupBox_8)
        self.label_115.setObjectName("label_115")
        self.formLayout_24.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_115)
        self.HODevWidthInFeatureSize = QtWidgets.QLineEdit(self.groupBox_8)
        self.HODevWidthInFeatureSize.setObjectName("HODevWidthInFeatureSize")
        self.formLayout_24.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevWidthInFeatureSize)
        self.HODevWidthSRAMCellNMOS = QtWidgets.QLineEdit(self.groupBox_8)
        self.HODevWidthSRAMCellNMOS.setObjectName("HODevWidthSRAMCellNMOS")
        self.formLayout_24.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HODevWidthSRAMCellNMOS)
        self.label_10 = QtWidgets.QLabel(self.groupBox_8)
        self.label_10.setObjectName("label_10")
        self.formLayout_24.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.HODevReadEnergySRAMCell = QtWidgets.QLineEdit(self.groupBox_8)
        self.HODevReadEnergySRAMCell.setObjectName("HODevReadEnergySRAMCell")
        self.formLayout_24.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HODevReadEnergySRAMCell)
        self.horizontalLayout_10.addLayout(self.formLayout_24)
        self.formLayout_25 = QtWidgets.QFormLayout()
        self.formLayout_25.setObjectName("formLayout_25")
        self.label_116 = QtWidgets.QLabel(self.groupBox_8)
        self.label_116.setObjectName("label_116")
        self.formLayout_25.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_116)
        self.HODevWidthSRAMCellPMOS = QtWidgets.QLineEdit(self.groupBox_8)
        self.HODevWidthSRAMCellPMOS.setObjectName("HODevWidthSRAMCellPMOS")
        self.formLayout_25.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevWidthSRAMCellPMOS)
        self.label_117 = QtWidgets.QLabel(self.groupBox_8)
        self.label_117.setObjectName("label_117")
        self.formLayout_25.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_117)
        self.label_118 = QtWidgets.QLabel(self.groupBox_8)
        self.label_118.setObjectName("label_118")
        self.formLayout_25.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_118)
        self.HODevWidthAccessCMOS = QtWidgets.QLineEdit(self.groupBox_8)
        self.HODevWidthAccessCMOS.setObjectName("HODevWidthAccessCMOS")
        self.formLayout_25.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevWidthAccessCMOS)
        self.HODevMinSenseVoltage = QtWidgets.QLineEdit(self.groupBox_8)
        self.HODevMinSenseVoltage.setObjectName("HODevMinSenseVoltage")
        self.formLayout_25.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HODevMinSenseVoltage)
        self.label_11 = QtWidgets.QLabel(self.groupBox_8)
        self.label_11.setObjectName("label_11")
        self.formLayout_25.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.HODevWriteEnergySRAMCell = QtWidgets.QLineEdit(self.groupBox_8)
        self.HODevWriteEnergySRAMCell.setObjectName("HODevWriteEnergySRAMCell")
        self.formLayout_25.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HODevWriteEnergySRAMCell)
        self.horizontalLayout_10.addLayout(self.formLayout_25)
        self.gridLayout_5.addWidget(self.groupBox_8, 2, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_23 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_23.setObjectName("formLayout_23")
        self.label_109 = QtWidgets.QLabel(self.groupBox_7)
        self.label_109.setObjectName("label_109")
        self.formLayout_23.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_109)
        self.HODevNLLTP = QtWidgets.QLineEdit(self.groupBox_7)
        self.HODevNLLTP.setObjectName("HODevNLLTP")
        self.formLayout_23.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HODevNLLTP)
        self.label_111 = QtWidgets.QLabel(self.groupBox_7)
        self.label_111.setObjectName("label_111")
        self.formLayout_23.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_111)
        self.HODevNLLTD = QtWidgets.QLineEdit(self.groupBox_7)
        self.HODevNLLTD.setObjectName("HODevNLLTD")
        self.formLayout_23.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HODevNLLTD)
        self.label_110 = QtWidgets.QLabel(self.groupBox_7)
        self.label_110.setObjectName("label_110")
        self.formLayout_23.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_110)
        self.HODevSigmaDtoD = QtWidgets.QLineEdit(self.groupBox_7)
        self.HODevSigmaDtoD.setObjectName("HODevSigmaDtoD")
        self.formLayout_23.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HODevSigmaDtoD)
        self.HODevConductanceRangeVar_2 = QtWidgets.QCheckBox(self.groupBox_7)
        self.HODevConductanceRangeVar_2.setObjectName("HODevConductanceRangeVar_2")
        self.formLayout_23.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HODevConductanceRangeVar_2)
        self.gridLayout_5.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.verticalLayout_2.addWidget(self.tabWidget_3)
        self.tabWidget.addTab(self.tabHO, "")
        self.tabData = QtWidgets.QWidget()
        self.tabData.setObjectName("tabData")
        self.formLayout_17 = QtWidgets.QFormLayout(self.tabData)
        self.formLayout_17.setObjectName("formLayout_17")
        self.trfp_l = QtWidgets.QLabel(self.tabData)
        self.trfp_l.setObjectName("trfp_l")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.trfp_l)
        self.trfp = QtWidgets.QLineEdit(self.tabData)
        self.trfp.setObjectName("trfp")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trfp)
        self.trfl_l = QtWidgets.QLabel(self.tabData)
        self.trfl_l.setObjectName("trfl_l")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.trfl_l)
        self.trfl = QtWidgets.QLineEdit(self.tabData)
        self.trfl.setObjectName("trfl")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.trfl)
        self.tefp_l = QtWidgets.QLabel(self.tabData)
        self.tefp_l.setObjectName("tefp_l")
        self.formLayout_17.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tefp_l)
        self.tefl_l = QtWidgets.QLabel(self.tabData)
        self.tefl_l.setObjectName("tefl_l")
        self.formLayout_17.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tefl_l)
        self.tefp = QtWidgets.QLineEdit(self.tabData)
        self.tefp.setObjectName("tefp")
        self.formLayout_17.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tefp)
        self.tefl = QtWidgets.QLineEdit(self.tabData)
        self.tefl.setObjectName("tefl")
        self.formLayout_17.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tefl)
        self.tabWidget.addTab(self.tabData, "")
        self.tabOutput = QtWidgets.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabOutput)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.output = QtWidgets.QTextEdit(self.tabOutput)
        self.output.setObjectName("output")
        self.gridLayout_4.addWidget(self.output, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabOutput, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.execute = QtWidgets.QPushButton(self.centralwidget)
        self.execute.setObjectName("execute")
        self.horizontalLayout.addWidget(self.execute)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        self.tabWidget_2.setCurrentIndex(4)
        self.tabWidget_3.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NeuroSim GUI"))
        self.label.setText(_translate("MainWindow", "MNISTTrainImgs"))
        self.MNISTTrainImgs.setText(_translate("MainWindow", "60000"))
        self.label_2.setText(_translate("MainWindow", "MNISTTestImgs"))
        self.MNISTTestImgs.setText(_translate("MainWindow", "10000"))
        self.TrainImgEpoch_l.setText(_translate("MainWindow", "TrainImgEpoch"))
        self.TrainImgEpoch.setText(_translate("MainWindow", "8000"))
        self.label_4.setText(_translate("MainWindow", "totEpoch"))
        self.totEpoch.setText(_translate("MainWindow", "125"))
        self.label_5.setText(_translate("MainWindow", "intEpoch"))
        self.intEpoch.setText(_translate("MainWindow", "1"))
        self.writeEReport.setText(_translate("MainWindow", "writeEReport"))
        self.SimDynPerf.setText(_translate("MainWindow", "SimDynPerf"))
        self.relaxArrCellH.setText(_translate("MainWindow", "relaxArrCellH"))
        self.relaxArrCellW.setText(_translate("MainWindow", "relaxArrCellW"))
        self.label_6.setText(_translate("MainWindow", "arrWireW"))
        self.arrWireW.setText(_translate("MainWindow", "100"))
        self.label_7.setText(_translate("MainWindow", "node"))
        self.node.setText(_translate("MainWindow", "32"))
        self.label_8.setText(_translate("MainWindow", "clkfq"))
        self.clkfq.setText(_translate("MainWindow", "2e9"))
        self.HWTrainFF.setText(_translate("MainWindow", "HWTrainFF"))
        self.HWTrainWU.setText(_translate("MainWindow", "HWTrainWU"))
        self.HWTestFF.setText(_translate("MainWindow", "HWTestFF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTrain), _translate("MainWindow", "Train"))
        self.label_31.setText(_translate("MainWindow", "nIn"))
        self.label_32.setText(_translate("MainWindow", "nHide"))
        self.label_33.setText(_translate("MainWindow", "nOut"))
        self.label_34.setText(_translate("MainWindow", "alp1"))
        self.label_35.setText(_translate("MainWindow", "alp2"))
        self.label_36.setText(_translate("MainWindow", "maxW"))
        self.label_37.setText(_translate("MainWindow", "minW"))
        self.label_38.setText(_translate("MainWindow", "opt"))
        self.nIn.setText(_translate("MainWindow", "400"))
        self.nHide.setText(_translate("MainWindow", "100"))
        self.nOut.setText(_translate("MainWindow", "10"))
        self.alp1.setText(_translate("MainWindow", "0.4"))
        self.alp2.setText(_translate("MainWindow", "0.2"))
        self.maxW.setText(_translate("MainWindow", "1.0"))
        self.minW.setText(_translate("MainWindow", "-1.0"))
        self.opt.setItemText(0, _translate("MainWindow", "SGD"))
        self.opt.setItemText(1, _translate("MainWindow", "Momentum"))
        self.opt.setItemText(2, _translate("MainWindow", "Adagrad"))
        self.opt.setItemText(3, _translate("MainWindow", "RMSprop"))
        self.opt.setItemText(4, _translate("MainWindow", "Adam"))
        self.label_39.setText(_translate("MainWindow", "nBitInput"))
        self.label_40.setText(_translate("MainWindow", "nBitPartial"))
        self.label_41.setText(_translate("MainWindow", "nWBit"))
        self.label_42.setText(_translate("MainWindow", "BWthres"))
        self.label_43.setText(_translate("MainWindow", "Hthres"))
        self.label_44.setText(_translate("MainWindow", "nColMux"))
        self.label_45.setText(_translate("MainWindow", "nWriteColMux"))
        self.nBitInput.setText(_translate("MainWindow", "1"))
        self.nBitPartial.setText(_translate("MainWindow", "9"))
        self.nWBit.setText(_translate("MainWindow", "6"))
        self.BWthres.setText(_translate("MainWindow", "0.5"))
        self.Hthres.setText(_translate("MainWindow", "0.5"))
        self.nColMux.setText(_translate("MainWindow", "16"))
        self.nWriteColMux.setText(_translate("MainWindow", "16"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Network"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Device Type"))
        self.IHSRAM.setText(_translate("MainWindow", "SRAM"))
        self.IHIdeal.setText(_translate("MainWindow", "IdealDevice"))
        self.IHReal.setText(_translate("MainWindow", "RealDevice"))
        self.IHDigitalNVM.setText(_translate("MainWindow", "DigitalNVM"))
        self.IHMeasured.setText(_translate("MainWindow", "Measured Device"))
        self.label_76.setText(_translate("MainWindow", "maxConductance"))
        self.IHDevMaxConductance.setText(_translate("MainWindow", "5e-6"))
        self.label_78.setText(_translate("MainWindow", "minConductance"))
        self.IHDevMinConductance.setText(_translate("MainWindow", "100e-9"))
        self.label_79.setText(_translate("MainWindow", "readVoltage"))
        self.IHDevReadVoltage.setText(_translate("MainWindow", "0.5"))
        self.label_81.setText(_translate("MainWindow", "readPulseWidth"))
        self.IHDevReadPulseWidth.setText(_translate("MainWindow", "5e-9"))
        self.label_82.setText(_translate("MainWindow", "writeVoltageLTP"))
        self.IHDevWriteVoltageLTP.setText(_translate("MainWindow", "2"))
        self.label_83.setText(_translate("MainWindow", "writeVoltageLTD"))
        self.IHDevWriteVoltageLTD.setText(_translate("MainWindow", "2"))
        self.label_84.setText(_translate("MainWindow", "writePulseWidthLTP"))
        self.IHDevWritePulseWidthLTP.setText(_translate("MainWindow", "10e-9"))
        self.label_80.setText(_translate("MainWindow", "writePulseWidthLTD"))
        self.IHDevWritePulseWidthLTD.setText(_translate("MainWindow", "10e-9"))
        self.label_77.setText(_translate("MainWindow", "readEnergy"))
        self.IHDevReadEnergy.setText(_translate("MainWindow", "0"))
        self.label_85.setText(_translate("MainWindow", "writeEnergy"))
        self.IHDevWriteEnergy.setText(_translate("MainWindow", "0"))
        self.label_89.setText(_translate("MainWindow", "resistanceAccess"))
        self.IHDevResistanceAccess.setText(_translate("MainWindow", "15e3"))
        self.label_91.setText(_translate("MainWindow", "NL"))
        self.IHDevNL.setText(_translate("MainWindow", "10"))
        self.label_86.setText(_translate("MainWindow", "sigmaReadNoise"))
        self.IHDevSigmaReadNoise.setText(_translate("MainWindow", "0.25"))
        self.IHDevCMOSAccess.setText(_translate("MainWindow", "CMOS Access"))
        self.IHDevNonlinearIV.setText(_translate("MainWindow", "nonlinearIV"))
        self.IHDevReadNoise.setText(_translate("MainWindow", "readNoise"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Public"))
        self.label_14.setText(_translate("MainWindow", "maxNumLevelLTP"))
        self.IHDevMaxNumLevelLTP.setText(_translate("MainWindow", "63"))
        self.label_15.setText(_translate("MainWindow", "maxNumLevelLTD"))
        self.IHDevMaxNumLevelLTD.setText(_translate("MainWindow", "63"))
        self.label_16.setText(_translate("MainWindow", "numPulse"))
        self.IHDevNumPulse.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "gateCapFeFET"))
        self.IHDevGateCapFeFET.setText(_translate("MainWindow", "2.1717e-18"))
        self.label_24.setText(_translate("MainWindow", "resistanceAccess"))
        self.IHDevResistanceAccess_2.setText(_translate("MainWindow", "15e3"))
        self.IHDevCMOSAccess_2.setText(_translate("MainWindow", "cmosAccess"))
        self.IHDevFeFET.setText(_translate("MainWindow", "FeFET"))
        self.label_20.setText(_translate("MainWindow", "maxConductanceVar"))
        self.IHDevMaxConductanceVar.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "minConductanceVar"))
        self.IHDevMinConductanceVar.setText(_translate("MainWindow", "0"))
        self.IHDevNonlinearIV_2.setText(_translate("MainWindow", "nonlinearIV"))
        self.IHDevNonIdenticalPulse.setText(_translate("MainWindow", "nonIdenticalPulse"))
        self.IHDevConductanceRangeVar.setText(_translate("MainWindow", "conductanceRangeVar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Ideal && Real && Measured"))
        self.label_59.setText(_translate("MainWindow", "VinitLTP"))
        self.IHDevVinitLTP.setText(_translate("MainWindow", "2.85"))
        self.label_60.setText(_translate("MainWindow", "VstepLTP"))
        self.IHDevVstepLTP.setText(_translate("MainWindow", "0.05"))
        self.label_61.setText(_translate("MainWindow", "VinitLTD"))
        self.IHDevVinitLTD.setText(_translate("MainWindow", "2.1"))
        self.label_62.setText(_translate("MainWindow", "VstepLTD"))
        self.IHDevVstepLTD.setText(_translate("MainWindow", "0.05"))
        self.label_63.setText(_translate("MainWindow", "PWinitLTP"))
        self.IHDevPWinitLTP.setText(_translate("MainWindow", "75e-9"))
        self.label_64.setText(_translate("MainWindow", "PWstepLTP"))
        self.IHDevPWstepLTP.setText(_translate("MainWindow", "5e-9"))
        self.IHDevNonlinearWrite.setText(_translate("MainWindow", "nonlinearWrite"))
        self.label_58.setText(_translate("MainWindow", "PWinitLTD"))
        self.IHDevPWinitLTD.setText(_translate("MainWindow", "75e-9"))
        self.label_65.setText(_translate("MainWindow", "PWstepLTD"))
        self.IHDevPWstepLTD.setText(_translate("MainWindow", "5e-9"))
        self.label_66.setText(_translate("MainWindow", "writeVoltageSquareSum"))
        self.IHDevWriteVoltageSquareSum.setText(_translate("MainWindow", "0"))
        self.label_67.setText(_translate("MainWindow", "writeLatencyLTP"))
        self.label_68.setText(_translate("MainWindow", "writeLatencyLTD"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Real && Measured"))
        self.label_70.setText(_translate("MainWindow", "bit"))
        self.label_71.setText(_translate("MainWindow", "bitPrev"))
        self.IHDevBit.setText(_translate("MainWindow", "0"))
        self.IHDevBitPrev.setText(_translate("MainWindow", "0"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "SRAM && Digital eNVM"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Digital eNVM"))
        self.IHDevParallelRead.setText(_translate("MainWindow", "parallelRead"))
        self.groupBox.setTitle(_translate("MainWindow", "Real Device"))
        self.label_46.setText(_translate("MainWindow", "NL_LTP"))
        self.label_50.setText(_translate("MainWindow", "sigmaDtoD"))
        self.label_51.setText(_translate("MainWindow", "NL_LTD"))
        self.IHDevNLLTP.setText(_translate("MainWindow", "2.4"))
        self.IHDevNLLTD.setText(_translate("MainWindow", "-4.88"))
        self.IHDevSigmaDtoD.setText(_translate("MainWindow", "0"))
        self.checkBox_2.setText(_translate("MainWindow", "conductanceRangeVar"))
        self.groupBox_4.setTitle(_translate("MainWindow", "SRAM"))
        self.label_52.setText(_translate("MainWindow", "heightInFeatureSize"))
        self.IHDevHeightInFeatureSize.setText(_translate("MainWindow", "14.6"))
        self.label_53.setText(_translate("MainWindow", "widthInFeatureSize"))
        self.label_55.setText(_translate("MainWindow", "widthSRAMCellNMOS"))
        self.IHDevWidthInFeatureSize.setText(_translate("MainWindow", "10"))
        self.IHDevWidthSRAMCellNMOS.setText(_translate("MainWindow", "2.08"))
        self.label_3.setText(_translate("MainWindow", "readEnergySRAMCell"))
        self.IHDevReadEnergySRAMCell.setText(_translate("MainWindow", "0"))
        self.label_48.setText(_translate("MainWindow", "widthSRAMCellPMOS"))
        self.IHDevWidthSRAMCellPMOS.setText(_translate("MainWindow", "1.23"))
        self.label_54.setText(_translate("MainWindow", "widthAccessCMOS"))
        self.label_56.setText(_translate("MainWindow", "minSenseVoltage"))
        self.IHDevWidthAccessCMOS.setText(_translate("MainWindow", "1.31"))
        self.IHDevMinSenseVoltage.setText(_translate("MainWindow", "0.1"))
        self.IHDevWriteEnergySRAMCell.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "writeEnergySRAMCell"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Measured Device"))
        self.IHDevSymLTPandLTD.setText(_translate("MainWindow", "symLTPandLTD"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Individuals"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIH), _translate("MainWindow", "IH Device"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Device Type"))
        self.HOReal.setText(_translate("MainWindow", "RealDevice"))
        self.HODigitalNVM.setText(_translate("MainWindow", "DigitalNVM"))
        self.HOIdeal.setText(_translate("MainWindow", "IdealDevice"))
        self.HOSRAM.setText(_translate("MainWindow", "SRAM"))
        self.HOMeasured.setText(_translate("MainWindow", "Measured Device"))
        self.label_92.setText(_translate("MainWindow", "maxConductance"))
        self.HODevMaxConductance.setText(_translate("MainWindow", "5e-6"))
        self.label_93.setText(_translate("MainWindow", "minConductance"))
        self.label_94.setText(_translate("MainWindow", "readVoltage"))
        self.label_95.setText(_translate("MainWindow", "writePulseWidthLTD"))
        self.label_96.setText(_translate("MainWindow", "readPulseWidth"))
        self.label_97.setText(_translate("MainWindow", "writeVoltageLTP"))
        self.label_98.setText(_translate("MainWindow", "writeVoltageLTD"))
        self.label_99.setText(_translate("MainWindow", "writePulseWidthLTP"))
        self.HODevMinConductance.setText(_translate("MainWindow", "100e-9"))
        self.HODevReadVoltage.setText(_translate("MainWindow", "0.5"))
        self.HODevReadPulseWidth.setText(_translate("MainWindow", "5e-9"))
        self.HODevWriteVoltageLTP.setText(_translate("MainWindow", "2"))
        self.HODevWriteVoltageLTD.setText(_translate("MainWindow", "2"))
        self.HODevWritePulseWidthLTP.setText(_translate("MainWindow", "10e-9"))
        self.HODevWritePulseWidthLTD.setText(_translate("MainWindow", "10e-9"))
        self.label_100.setText(_translate("MainWindow", "readEnergy"))
        self.HODevReadEnergy.setText(_translate("MainWindow", "0"))
        self.label_101.setText(_translate("MainWindow", "writeEnergy"))
        self.HODevWriteEnergy.setText(_translate("MainWindow", "0"))
        self.label_105.setText(_translate("MainWindow", "resistanceAccess"))
        self.HODevResistanceAccess.setText(_translate("MainWindow", "15e3"))
        self.label_107.setText(_translate("MainWindow", "NL"))
        self.HODevNL.setText(_translate("MainWindow", "10"))
        self.label_102.setText(_translate("MainWindow", "sigmaReadNoise"))
        self.HODevSigmaReadNoise.setText(_translate("MainWindow", "0.25"))
        self.HODevCMOSAccess.setText(_translate("MainWindow", "CMOS Access"))
        self.HODevNonlinearIV.setText(_translate("MainWindow", "nonlinearIV"))
        self.HODevReadNoise.setText(_translate("MainWindow", "readNoise"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Public"))
        self.label_125.setText(_translate("MainWindow", "maxNumLevelLTP"))
        self.HODevMaxNumLevelLTP.setText(_translate("MainWindow", "63"))
        self.label_126.setText(_translate("MainWindow", "maxNumLevelLTD"))
        self.HODevMaxNumLevelLTD.setText(_translate("MainWindow", "63"))
        self.label_127.setText(_translate("MainWindow", "numPulse"))
        self.HODevNumPulse.setText(_translate("MainWindow", "0"))
        self.label_130.setText(_translate("MainWindow", "gateCapFeFET"))
        self.HODevGateCapFeFET.setText(_translate("MainWindow", "2.1717e-18"))
        self.label_131.setText(_translate("MainWindow", "resistanceAccess"))
        self.HODevResistanceAccess_2.setText(_translate("MainWindow", "15e3"))
        self.HODevCMOSAccess_2.setText(_translate("MainWindow", "cmosAccess"))
        self.HODevFeFET.setText(_translate("MainWindow", "FeFET"))
        self.label_123.setText(_translate("MainWindow", "maxConductanceVar"))
        self.HODevMaxConductanceVar.setText(_translate("MainWindow", "0"))
        self.label_124.setText(_translate("MainWindow", "minConductanceVar"))
        self.HODevMinConductanceVar.setText(_translate("MainWindow", "0"))
        self.HODevConductanceRangeVar.setText(_translate("MainWindow", "conductanceRangeVar"))
        self.HODevNonlinearIV_2.setText(_translate("MainWindow", "nonlinearIV"))
        self.HODevNonIdenticalPulse.setText(_translate("MainWindow", "nonIdenticalPulse"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Ideal && Real && Measured"))
        self.label_133.setText(_translate("MainWindow", "VinitLTP"))
        self.HODevVinitLTP.setText(_translate("MainWindow", "2.85"))
        self.label_134.setText(_translate("MainWindow", "VstepLTP"))
        self.HODevVstepLTP.setText(_translate("MainWindow", "0.05"))
        self.label_135.setText(_translate("MainWindow", "VinitLTD"))
        self.HODevVinitLTD.setText(_translate("MainWindow", "2.1"))
        self.label_136.setText(_translate("MainWindow", "VstepLTD"))
        self.HODevVstepLTD.setText(_translate("MainWindow", "0.05"))
        self.label_137.setText(_translate("MainWindow", "PWinitLTP"))
        self.HODevPWinitLTP.setText(_translate("MainWindow", "75e-9"))
        self.label_138.setText(_translate("MainWindow", "PWstepLTP"))
        self.HODevPWstepLTP.setText(_translate("MainWindow", "5e-9"))
        self.HODevNonlinearWrite.setText(_translate("MainWindow", "nonlinearWrite"))
        self.label_139.setText(_translate("MainWindow", "PWinitLTD"))
        self.HODevPWinitLTD.setText(_translate("MainWindow", "75e-9"))
        self.label_140.setText(_translate("MainWindow", "PWstepLTD"))
        self.HODevPWstepLTD.setText(_translate("MainWindow", "5e-9"))
        self.label_141.setText(_translate("MainWindow", "writeVoltageSquareSum"))
        self.HODevWriteVoltageSquareSum.setText(_translate("MainWindow", "0"))
        self.label_142.setText(_translate("MainWindow", "writeLatencyLTP"))
        self.label_143.setText(_translate("MainWindow", "writeLatencyLTD"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Real && Measured"))
        self.label_145.setText(_translate("MainWindow", "bit"))
        self.label_146.setText(_translate("MainWindow", "bitPrev"))
        self.HODevBit.setText(_translate("MainWindow", "0"))
        self.HODevBitPrev.setText(_translate("MainWindow", "0"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MainWindow", "SRAM && Digital eNVM"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Measured Device"))
        self.HODevSymLTPandLTD.setText(_translate("MainWindow", "symLTPandLTD"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Digital eNVM"))
        self.HODevParallelRead.setText(_translate("MainWindow", "parallelRead"))
        self.groupBox_8.setTitle(_translate("MainWindow", "SRAM"))
        self.label_113.setText(_translate("MainWindow", "heightInFeatureSize"))
        self.HODevHeightInFeatureSize.setText(_translate("MainWindow", "14.6"))
        self.label_114.setText(_translate("MainWindow", "widthInFeatureSize"))
        self.label_115.setText(_translate("MainWindow", "widthSRAMCellNMOS"))
        self.HODevWidthInFeatureSize.setText(_translate("MainWindow", "10"))
        self.HODevWidthSRAMCellNMOS.setText(_translate("MainWindow", "2.08"))
        self.label_10.setText(_translate("MainWindow", "readEnergySRAMCell"))
        self.HODevReadEnergySRAMCell.setText(_translate("MainWindow", "0"))
        self.label_116.setText(_translate("MainWindow", "widthSRAMCellPMOS"))
        self.HODevWidthSRAMCellPMOS.setText(_translate("MainWindow", "2.08"))
        self.label_117.setText(_translate("MainWindow", "widthAccessCMOS"))
        self.label_118.setText(_translate("MainWindow", "minSenseVoltage"))
        self.HODevWidthAccessCMOS.setText(_translate("MainWindow", "1.31"))
        self.HODevMinSenseVoltage.setText(_translate("MainWindow", "0.1"))
        self.label_11.setText(_translate("MainWindow", "writeEnergySRAMCell"))
        self.HODevWriteEnergySRAMCell.setText(_translate("MainWindow", "0"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Real Device"))
        self.label_109.setText(_translate("MainWindow", "NL_LTP"))
        self.HODevNLLTP.setText(_translate("MainWindow", "2.4"))
        self.label_111.setText(_translate("MainWindow", "NL_LTD"))
        self.HODevNLLTD.setText(_translate("MainWindow", "-4.88"))
        self.label_110.setText(_translate("MainWindow", "sigmaDtoD"))
        self.HODevSigmaDtoD.setText(_translate("MainWindow", "0"))
        self.HODevConductanceRangeVar_2.setText(_translate("MainWindow", "conductanceRangeVar"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Individuals"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHO), _translate("MainWindow", "HO Device"))
        self.trfp_l.setText(_translate("MainWindow", "trfp"))
        self.trfp.setText(_translate("MainWindow", "patch60000_train.txt"))
        self.trfl_l.setText(_translate("MainWindow", "trfl"))
        self.trfl.setText(_translate("MainWindow", "label60000_train.txt"))
        self.tefp_l.setText(_translate("MainWindow", "tefp"))
        self.tefl_l.setText(_translate("MainWindow", "tefl"))
        self.tefp.setText(_translate("MainWindow", "patch10000_test.txt"))
        self.tefl.setText(_translate("MainWindow", "label10000_test.txt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabData), _translate("MainWindow", "Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutput), _translate("MainWindow", "Output"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.execute.setText(_translate("MainWindow", "Execute"))
